KN_ProyectoWeb/Models/Producto.cs
namespace KN_ProyectoWeb.Models
{
    public class Producto
    {


        public int IdProducto { get; set; }

        public string Nombre { get; set; }

        public string Descripcion { get; set; }


        public decimal Precio { get; set; }

        public int IdCategoria { get; set; }

        public bool Estado { get; set; }

        public string Imagen { get; set; }




    }
}

KN_ProyectoWeb/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KN_ProyectoWeb.Models
{
    public class Usuario
    {
        public string Identificacion { get; set; }

        public string Nombre { get; set; }



        public string CorreoElectronico { get; set; }



        public string Contrasenna { get; set; }






    }
}

KN_ProyectoWeb/Controllers/HomeController.cs
using KN_ProyectoWeb.EF;
using KN_ProyectoWeb.Models;
using KN_ProyectoWeb.Services;
using System;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Security.Cryptography;
using System.Text;
using System.Web.Mvc;

namespace KN_ProyectoWeb.Controllers
{
    public class HomeController : Controller
    {
        Utilitarios utilitarios = new Utilitarios();

        #region Iniciar Sesion


        #region Registro

        #region RecuperarAcceso

        [HttpGet]
        public ActionResult Index()

        {
            return View();
        }



        [HttpPost]
        public ActionResult Index(Usuario usuario)

        {

            /*Progra para ir al iniciar sesion a la BD*/

            using (var context = new BD_KNEntities())
            {

                //var resultado = context.tbUsuario.Where(x => x.CorreoElectronico == usuario.CorreoElectronico
                //                                                                                && x.Contrasenna == usuario.Contrasenna
                //                                                                                && x.Estado == true).FirstOrDefault();


                var resultado = context.ValidarUsuarios(usuario.CorreoElectronico, usuario.Contrasenna).FirstOrDefault();


                if (resultado != null)


                {
                    Session["NombreUsuario"] = resultado.Nombre;
                    return RedirectToAction("Principal", "Home");

                }

                ViewBag.Mensaje = "La informacion no se ha podido registrar";

                return View();





            }



        }

        #endregion




        [HttpGet]
        public ActionResult Registro()
        {
            return View();

        }


        [HttpPost]
        public ActionResult Registro(Usuario usuario)



        {


            using (var context = new BD_KNEntities())
            {
                //var nuevoUsuario = new tbUsuario
                //{

                //    Identificacion = usuario.Identificacion,
                //    Nombre = usuario.Nombre,
                //    CorreoElectronico = usuario.CorreoElectronico,
                //    Contrasenna = usuario.Contrasenna,
                //    idPerfil = 2,
                //    Estado = true



                //};

                //context.tbUsuario.Add(nuevoUsuario);
                //context.SaveChanges();

                var resultado = context
                    .CrearUsuarios(usuario.Identificacion, usuario.Nombre, usuario.CorreoElectronico, usuario.Contrasenna)
                    .FirstOrDefault();


                if (resultado > 0)
                {
                    return RedirectToAction("Index", "home");
                }


                ViewBag.Mensaje = "La informacion no se ha podido registrar.";
                return View();



            }

            /*Progra para ir a guardar el usuario a la BD*/


        }
        #endregion





        [HttpGet]
        public ActionResult RecuperarAcceso()
        {
            return View();
        }


        [HttpPost]
        public ActionResult RecuperarAcceso(Usuario usuario)
        {
            using (var context = new BD_KNEntities())
            {
                //Actualizar la contrasenna del usuario
                var resultadoConsulta = context.tbUsuario
                    .Where(x => x.CorreoElectronico == usuario.CorreoElectronico).FirstOrDefault();





                if (resultadoConsulta != null)
                {

                    var contrasennaGenerada = utilitarios.GenerarContrasenna();


                    //Actualizar la nueva contraseña
                    resultadoConsulta.Contrasenna = contrasennaGenerada;
                    var resultadoActualizacion = context.SaveChanges();



                    //Envia el correo Electronico al usuario con la nueva contrasenna
                    if (resultadoActualizacion > 0)
                    {
                        //StringBuilder mensaje = new StringBuilder();
                        //mensaje.Append("Estimado(a) " + resultadoConsulta.Nombre + "<br>");
                        //mensaje.Append("Se ha generado una solicitud de recuperación de acceso a su nombre." + "<br><br>");
                        //mensaje.Append("Su nueva contraseña de acceso es: " + contrasennaGenerada + "<br><br>");
                        //mensaje.Append("Procure realizar el cambio de su contraseña una vez ingrese al sistema.<br>");
                        //mensaje.Append("Muchas gracias.");



                        string projectRoot = AppDomain.CurrentDomain.BaseDirectory;
                        string path = Path.Combine(projectRoot, "TemplateRecuperacion.html");

                        // Leer todo el HTML
                        string htmlTemplate = System.IO.File.ReadAllText(path);


                        // Reemplazar placeholders
                        string mensaje = htmlTemplate
                            .Replace("{{Nombre}}", resultadoConsulta.Nombre)
                            .Replace("{{Contrasena}}", contrasennaGenerada);





                        utilitarios.EnviarCorreo("Contraseña de acceso", mensaje, resultadoConsulta.CorreoElectronico);

                        return RedirectToAction("Index", "Home");



                    }



                    //Esta es su nueva contrasenna


                }






                ViewBag.Mensaje = "La informacion no se ha podido restablecer .";

                return View();
            }
        }

        #endregion

        [HttpGet]

        public ActionResult Principal()
        {
            return View();
        }

        [HttpGet]
        public ActionResult CerrarSesion()
        {

            Session.Clear();


            return RedirectToAction("Index", "Home");
        }



    }
    
}

KN_ProyectoWeb/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KN_ProyectoWeb.Controllers
{
    public class ProductosController : Controller
    {

        #region VerProductos
        [HttpGet]
        public ActionResult VerProductos()


        {


            using (var context = new EF.BD_KNEntities())
            {

                var productos = context.tbProducto.Include("tbCategoria").ToList();



                return View(productos);
            }


        }
            
                
        }


        

        #endregion
    }

KN_ProyectoWeb/Views/Home/Index.cshtml
@model KN_ProyectoWeb.Models.Usuario

@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_LayoutExterno.cshtml";
}

<div class="authentication-wrapper authentication-basic container-p-y">
    <div class="authentication-inner">
        <!-- Login -->
        <div class="card">
            <div class="card-body">
                <!-- Logo -->
                <div class="app-brand justify-content-center">
                    <a href="@Url.Action("Index","Home")" class="app-brand-link gap-2">
                        <img src="~/StaticFiles/img/Icono.png" alt="Logo" style="height:48px;" />
                        <span class="app-brand-text demo text-body fw-bolder">Iniciar Sesión</span>
                    </a>
                </div>

                @if (ViewBag.Mensaje != null)
                {
                    <div class="alert alert-primary" role="alert">
                        @ViewBag.Mensaje
                    </div>
                }

                @using (Html.BeginForm("Index", "Home", FormMethod.Post, new { id = "FormIniciarSesion" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="mb-3">
                        <label for="CorreoElectronico" class="form-label">Correo Electrónico</label>
                        @Html.TextBoxFor(m => m.CorreoElectronico, new
                        {
                            @class = "form-control",
                            @type = "email",
                            @placeholder = "correo@dominio.com",
                            @autocomplete = "username",
                            required = "required"
                        })
                        @Html.ValidationMessageFor(m => m.CorreoElectronico, "", new { @class = "text-danger" })
                    </div>

                    <div class="mb-3 form-password-toggle">
                        <div class="d-flex justify-content-between">
                            <label class="form-label" for="Contrasenna">Contraseña</label>
                            <a href="@Url.Action("RecuperarAcceso", "Home")">
                                <small>¿Olvidó su contraseña?</small>
                            </a>
                        </div>
                        <div class="input-group input-group-merge">
                            <input type="password"
                                   id="Contrasenna"
                                   name="Contrasenna"
                                   class="form-control"
                                   placeholder="Ingrese su contraseña"
                                   autocomplete="current-password"
                                   required />
                            <span class="input-group-text cursor-pointer">
                                <i class="bx bx-hide"></i>
                            </span>
                        </div>
                        @Html.ValidationMessage("Contrasenna", "", new { @class = "text-danger" })
                    </div>

                    <div class="mb-3">
                        <button class="btn btn-primary d-grid w-100" type="submit">Iniciar Sesión</button>
                    </div>
                }

                <p class="text-center">
                    <span>¿Nuevo en nuestra plataforma?</span>
                    <a href="@Url.Action("Registro", "Home")">
                        <span>Crear una cuenta</span>
                    </a>
                </p>
            </div>
        </div>
        <!-- /Login -->
    </div>
</div>

<script src="~/StaticFiles/js/IniciarSesion.js"></script>

KN_ProyectoWeb/Views/Home/Principal.cshtml
@{
    
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}

KN_ProyectoWeb/Views/Home/RecuperarAcceso.cshtml
@model KN_ProyectoWeb.Models.Usuario


@{

    Layout = "~/Views/Shared/_LayoutExterno.cshtml";
}


<div class="container-xxl">
    <div class="authentication-wrapper authentication-basic container-p-y">
        <div class="authentication-inner py-4">
          
            <div class="card">
                <div class="card-body">

                    <div class="app-brand justify-content-center">
                        <a href="index.html" class="app-brand-link gap-2">
                            <span class="app-brand-logo demo">
                                <svg width="25"
                                     viewBox="0 0 25 42"
                                     version="1.1"
                                     xmlns="http://www.w3.org/2000/svg"
                                     xmlns:xlink="http://www.w3.org/1999/xlink">
                                    <defs>
                                        <path d="M13.7918663,0.358365126 L3.39788168,7.44174259 C0.566865006,9.69408886 -0.379795268,12.4788597 0.557900856,15.7960551 C0.68998853,16.2305145 1.09562888,17.7872135 3.12357076,19.2293357 C3.8146334,19.7207684 5.32369333,20.3834223 7.65075054,21.2172976 L7.59773219,21.2525164 L2.63468769,24.5493413 C0.445452254,26.3002124 0.0884951797,28.5083815 1.56381646,31.1738486 C2.83770406,32.8170431 5.20850219,33.2640127 7.09180128,32.5391577 C8.347334,32.0559211 11.4559176,30.0011079 16.4175519,26.3747182 C18.0338572,24.4997857 18.6973423,22.4544883 18.4080071,20.2388261 C17.963753,17.5346866 16.1776345,15.5799961 13.0496516,14.3747546 L10.9194936,13.4715819 L18.6192054,7.984237 L13.7918663,0.358365126 Z"
                                              id="path-1"></path>
                                        <path d="M5.47320593,6.00457225 C4.05321814,8.216144 4.36334763,10.0722806 6.40359441,11.5729822 C8.61520715,12.571656 10.0999176,13.2171421 10.8577257,13.5094407 L15.5088241,14.433041 L18.6192054,7.984237 C15.5364148,3.11535317 13.9273018,0.573395879 13.7918663,0.358365126 C13.5790555,0.511491653 10.8061687,2.3935607 5.47320593,6.00457225 Z"
                                              id="path-3"></path>
                                        <path d="M7.50063644,21.2294429 L12.3234468,23.3159332 C14.1688022,24.7579751 14.397098,26.4880487 13.008334,28.506154 C11.6195701,30.5242593 10.3099883,31.790241 9.07958868,32.3040991 C5.78142938,33.4346997 4.13234973,34 4.13234973,34 C4.13234973,34 2.75489982,33.0538207 2.37032616e-14,31.1614621 C-0.55822714,27.8186216 -0.55822714,26.0572515 -4.05231404e-15,25.8773518 C0.83734071,25.6075023 2.77988457,22.8248993 3.3049379,22.52991 C3.65497346,22.3332504 5.05353963,21.8997614 7.50063644,21.2294429 Z"
                                              id="path-4"></path>
                                        <path d="M20.6,7.13333333 L25.6,13.8 C26.2627417,14.6836556 26.0836556,15.9372583 25.2,16.6 C24.8538077,16.8596443 24.4327404,17 24,17 L14,17 C12.8954305,17 12,16.1045695 12,15 C12,14.5672596 12.1403557,14.1461923 12.4,13.8 L17.4,7.13333333 C18.0627417,6.24967773 19.3163444,6.07059163 20.2,6.73333333 C20.3516113,6.84704183 20.4862915,6.981722 20.6,7.13333333 Z"
                                              id="path-5"></path>
                                    </defs>
                                    <g id="g-app-brand" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <g id="Brand-Logo" transform="translate(-27.000000, -15.000000)">
                                            <g id="Icon" transform="translate(27.000000, 15.000000)">
                                                <g id="Mask" transform="translate(0.000000, 8.000000)">
                                                    <mask id="mask-2" fill="white">
                                                        <use xlink:href="#path-1"></use>
                                                    </mask>
                                                    <use fill="#696cff" xlink:href="#path-1"></use>
                                                    <g id="Path-3" mask="url(#mask-2)">
                                                        <use fill="#696cff" xlink:href="#path-3"></use>
                                                        <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-3"></use>
                                                    </g>
                                                    <g id="Path-4" mask="url(#mask-2)">
                                                        <use fill="#696cff" xlink:href="#path-4"></use>
                                                        <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-4"></use>
                                                    </g>
                                                </g>
                                                <g id="Triangle"
                                                   transform="translate(19.000000, 11.000000) rotate(-300.000000) translate(-19.000000, -11.000000) ">
                                                    <use fill="#696cff" xlink:href="#path-5"></use>
                                                    <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-5"></use>
                                                </g>
                                            </g>
                                        </g>
                                    </g>
                                </svg>
                            </span>
                            <span class="app-brand-text demo text-body fw-bolder">Olvidaste tu Contraseña?</span>
                        </a>
                    </div>

                    @if (ViewBag.Mensaje != null)
                    {
                        <div class="alert alert-primary" role="alert">
                            @ViewBag.Mensaje
                        </div>
                    }

                    @using (Html.BeginForm("RecuperarAcceso", "Home", FormMethod.Post, new { @id = "FormRecuperarAcceso" }))
                    {


                        <div class="mb-3">
                            <label for="email" class="form-label">Email</label>
                            @Html.TextBoxFor(x => x.CorreoElectronico, new { @class = "form-control", @type = "email" })

                        </div>
                        <button class="btn btn-primary d-grid w-100" type="submit">Procesar</button>
                    }
                    <div class="text-center">
                        <a href="@Url.Action("Index", "Home")" class="d-flex align-items-center justify-content-center">
                            <i class="bx bx-chevron-left scaleX-n1-rtl bx-sm"></i>
                            Regresar al Login
                        </a>
                    </div>
                </div>
            </div>
         
        </div>
    </div>
</div>

<script src="~/StaticFiles/js/RecuperarAcceso.js"></script>

KN_ProyectoWeb/Views/Shared/_LayoutInterno.cshtml
@{ 
    var nombreUsuario = (Session["NombreUsuario"] == null ? "Invitado " : Session["NombreUsuario"].ToString());
}



<!DOCTYPE html>


<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title>Proyecto Web</title>

    <meta name="description" content="" />



    <link rel="stylesheet" href="../StaticFiles/css/boxicons.css" />
    <link href="~/StaticFiles/css/core.css" rel="stylesheet" />
    <link href="~/StaticFiles/css/theme-default.css" rel="stylesheet" />
    <link href="~/StaticFiles/css/demo.css" rel="stylesheet" />
    <link href="~/StaticFiles/css/perfect-scrollbar.css" rel="stylesheet" />
    <link href="~/StaticFiles/css/page-auth.css" rel="stylesheet" />
    <script src="~/StaticFiles/js/helpers.js"></script>
    <script src="~/StaticFiles/js/config.js"></script>

    @*<script src="~/StaticFiles/js/jquery.js"></script>*@


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
</head>

<body>
    
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
            

            <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
                <div class="app-brand demo">
                    <a href="index.html" class="app-brand-link">
                        <span class="app-brand-logo demo">
                            <svg width="25"
                                 viewBox="0 0 25 42"
                                 version="1.1"
                                 xmlns="http://www.w3.org/2000/svg"
                                 xmlns:xlink="http://www.w3.org/1999/xlink">
                                <defs>
                                    <path d="M13.7918663,0.358365126 L3.39788168,7.44174259 C0.566865006,9.69408886 -0.379795268,12.4788597 0.557900856,15.7960551 C0.68998853,16.2305145 1.09562888,17.7872135 3.12357076,19.2293357 C3.8146334,19.7207684 5.32369333,20.3834223 7.65075054,21.2172976 L7.59773219,21.2525164 L2.63468769,24.5493413 C0.445452254,26.3002124 0.0884951797,28.5083815 1.56381646,31.1738486 C2.83770406,32.8170431 5.20850219,33.2640127 7.09180128,32.5391577 C8.347334,32.0559211 11.4559176,30.0011079 16.4175519,26.3747182 C18.0338572,24.4997857 18.6973423,22.4544883 18.4080071,20.2388261 C17.963753,17.5346866 16.1776345,15.5799961 13.0496516,14.3747546 L10.9194936,13.4715819 L18.6192054,7.984237 L13.7918663,0.358365126 Z"
                                          id="path-1"></path>
                                    <path d="M5.47320593,6.00457225 C4.05321814,8.216144 4.36334763,10.0722806 6.40359441,11.5729822 C8.61520715,12.571656 10.0999176,13.2171421 10.8577257,13.5094407 L15.5088241,14.433041 L18.6192054,7.984237 C15.5364148,3.11535317 13.9273018,0.573395879 13.7918663,0.358365126 C13.5790555,0.511491653 10.8061687,2.3935607 5.47320593,6.00457225 Z"
                                          id="path-3"></path>
                                    <path d="M7.50063644,21.2294429 L12.3234468,23.3159332 C14.1688022,24.7579751 14.397098,26.4880487 13.008334,28.506154 C11.6195701,30.5242593 10.3099883,31.790241 9.07958868,32.3040991 C5.78142938,33.4346997 4.13234973,34 4.13234973,34 C4.13234973,34 2.75489982,33.0538207 2.37032616e-14,31.1614621 C-0.55822714,27.8186216 -0.55822714,26.0572515 -4.05231404e-15,25.8773518 C0.83734071,25.6075023 2.77988457,22.8248993 3.3049379,22.52991 C3.65497346,22.3332504 5.05353963,21.8997614 7.50063644,21.2294429 Z"
                                          id="path-4"></path>
                                    <path d="M20.6,7.13333333 L25.6,13.8 C26.2627417,14.6836556 26.0836556,15.9372583 25.2,16.6 C24.8538077,16.8596443 24.4327404,17 24,17 L14,17 C12.8954305,17 12,16.1045695 12,15 C12,14.5672596 12.1403557,14.1461923 12.4,13.8 L17.4,7.13333333 C18.0627417,6.24967773 19.3163444,6.07059163 20.2,6.73333333 C20.3516113,6.84704183 20.4862915,6.981722 20.6,7.13333333 Z"
                                          id="path-5"></path>
                                </defs>
                                <g id="g-app-brand" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                    <g id="Brand-Logo" transform="translate(-27.000000, -15.000000)">
                                        <g id="Icon" transform="translate(27.000000, 15.000000)">
                                            <g id="Mask" transform="translate(0.000000, 8.000000)">
                                                <mask id="mask-2" fill="white">
                                                    <use xlink:href="#path-1"></use>
                                                </mask>
                                                <use fill="#696cff" xlink:href="#path-1"></use>
                                                <g id="Path-3" mask="url(#mask-2)">
                                                    <use fill="#696cff" xlink:href="#path-3"></use>
                                                    <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-3"></use>
                                                </g>
                                                <g id="Path-4" mask="url(#mask-2)">
                                                    <use fill="#696cff" xlink:href="#path-4"></use>
                                                    <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-4"></use>
                                                </g>
                                            </g>
                                            <g id="Triangle"
                                               transform="translate(19.000000, 11.000000) rotate(-300.000000) translate(-19.000000, -11.000000) ">
                                                <use fill="#696cff" xlink:href="#path-5"></use>
                                                <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-5"></use>
                                            </g>
                                        </g>
                                    </g>
                                </g>
                            </svg>
                        </span>
                        <span class="app-brand-text demo menu-text fw-bolder ms-2">KN WEB</span>
                    </a>

                    <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
                        <i class="bx bx-chevron-left bx-sm align-middle"></i>
                    </a>
                </div>

                <div class="menu-inner-shadow"></div>

                <ul class="menu-inner py-1">
                   

                    <li class="menu-header small text-uppercase">
                        <span class="menu-header-text">Mantenimiento</span>
                    </li>
                    <li class="menu-item">
                        <a href="@Url.Action("VerProductos", "Productos")" class="menu-link">
                            <i class="menu-icon tf-icons bx bx-home-circle"></i>
                            <div data-i18n="Analytics">Productos</div>
                        </a>
                    </li>
                 
                   
            </aside>
            
            <div class="layout-page">
              
                <nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
                     id="layout-navbar">
                    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
                        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                            <i class="bx bx-menu bx-sm"></i>
                        </a>
                    </div>

                    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
                        <div class="navbar-nav align-items-center">
                            <div class="nav-item d-flex align-items-center">
                                <i class="bx bx-search fs-4 lh-0"></i>
                                <input type="text"
                                       class="form-control border-0 shadow-none"
                                       placeholder="Search..."
                                       aria-label="Search..." />
                            </div>
                        </div>
                        

                        <ul class="navbar-nav flex-row align-items-center ms-auto">
                            

                            
                            <li class="nav-item navbar-dropdown dropdown-user dropdown">
                                <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                                    
                                        @nombreUsuario
                                    
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end">
                                    <li>
                                        <a class="dropdown-item" href="#">
                                            <div class="d-flex">
                                                <div class="flex-shrink-0 me-3">
                                                   
                                                </div>
                                                <div class="flex-grow-1">
                                                    <small class="text-muted">Admin</small>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <div class="dropdown-divider"></div>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="#">
                                            <i class="bx bx-user me-2"></i>
                                            <span class="align-middle">Perfil</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="#">
                                            <i class="bx bx-cog me-2"></i>
                                            <span class="align-middle">Seguridad</span>
                                        </a>
                                    </li>
                                   
                                    <li>
                                        <div class="dropdown-divider"></div>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" @Url.Action("CerrarSesion", "Home")>
                                            <i class="bx bx-power-off me-2"></i>
                                            <span class="align-middle">Cerrar Sesion</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                  
                        </ul>
                    </div>
                </nav>

                
                <div class="content-wrapper">
                    

                    <div class="container-xxl flex-grow-1 container-p-y">

                        @RenderBody()
                      
                        <div class="layout-demo-wrapper">
                            <div class="layout-demo-placeholder">
                              
                            </div>
                            
                        </div>
                      
                    </div>
                    
                    <footer class="content-footer footer bg-footer-theme">
                        <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
                            <div class="mb-2 mb-md-0">
                                ©
                                @DateTime.Now.Year, made with ❤️ by
                                <a href="https://themeselection.com" target="_blank" class="footer-link fw-bolder">ThemeSelection</a>
                            </div>
                         
                        </div>
                    </footer>
                   

                    <div class="content-backdrop fade"></div>
                </div>
             
            </div>
          
        </div>


        <div class="layout-overlay layout-menu-toggle"></div>
    </div>
   }

    


    <script src="~/StaticFiles/js/popper.js"></script>


    <script src="~/StaticFiles/js/bootstrap.js"></script>

    <script src="~/StaticFiles/js/perfect-scrollbar.js"></script>
    <script src="~/StaticFiles/js/menu.js"></script>
    <script src="~/StaticFiles/js/main.js"></script>

    <script async defer src="https://buttons.github.io/buttons.js"></script>
</body>
</html>